services:
  - name: nats-server
    type: web
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /healthz
    healthCheckIntervalSeconds: 30
    ports:
      - port: 4222
        containerPort: 4222
        protocol: TCP
      - port: 6222
        containerPort: 6222
        protocol: TCP
      - port: 8222
        containerPort: 8222
        protocol: TCP
